apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demo-crypto-screener
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: crypto-screener
spec:
  source:
    git:
      url: https://github.com/blankpge/CryptoCurrency-Screener.git
      ref:
        branch: main